export {default as BannerSection } from "./bannerSection"
export { default as SocialMediaSection } from "./socialMediaSection"
export { default as DeadQueenSection } from "./deadQueenSection"
export { default as CollectionsSection } from "./collectionsSection"
export { default as IdleQuestsSection } from "./idleQuestsSection"
export { default as RoadMapSection } from "./roadMapSection"
