export { default as Paper_1 } from "./paper_1"
export { default as Paper_2 } from "./paper_2"
export { default as Paper_3 } from "./paper_3"
export { default as Paper_4 } from "./paper_4"
export { default as PropStamp } from "./propStamp"
export { default as MapButton } from "./mapButton"
export { default as DropBox } from "./dropbox"