on: 
  push:
    branches: 
    - mainnet
name: Docker Preprod Publish
jobs:

  Docker-Proprod-Publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        deno-version: [1.34.x]

    steps:

    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Backend - build 
      working-directory: backend 
      run: |
        npm ci
        npm run build

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"

    - name: Login Digital Ocean Container Registry
      run: |
        docker login -u ${{ secrets.DIGITAL_OCEAN_API_TOKEN }} -p ${{ secrets.DIGITAL_OCEAN_API_TOKEN }} registry.digitalocean.com

    - name: Backend - Build, tag, and push
      id: docker-build-push-backend
      working-directory: backend
      env:
        REGISTRY: registry.digitalocean.com/ddu-cr
        REPOSITORY: ddu-backend
        IMAGE_TAG: mainnet # a-${{ steps.date.outputs.date }}-${{ github.sha }}
        ENCRYPTION_SALT: ${{ secrets.ENCRYPTION_SALT_MAINNET }}
      run: |
        echo "Image name $REGISTRY/$REPOSITORY:$IMAGE_TAG"
        npm run secrets:replace
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Frontend - Build, tag, and push
      id: docker-build-push-frontend
      working-directory: frontend
      env:
        REGISTRY: registry.digitalocean.com/ddu-cr
        REPOSITORY: ddu-frontend
        IMAGE_TAG: mainnet # a-${{ steps.date.outputs.date }}-${{ github.sha }}
      run: |
        echo "Image name $REGISTRY/$REPOSITORY:$IMAGE_TAG"
        echo -e "NEXT_PUBLIC_ENVIROMENT=production" >> .env.local 
        echo -e "NEXT_PUBLIC_API_BASE_HOSTNAME=https://ddu.gg" >> .env.local 
        echo -e "NEXT_PUBLIC_CARDANO_NETWORK=Mainnet" >> .env.local 
        echo -e "NEXT_PUBLIC_BLOCKFROST_API_KEY=${{ secrets.BLOCKFROST_API_KEY_MAINNET }}" >> .env.local 
        echo -e "NEXT_PUBLIC_DISCORD_CLIENT_ID='1017194651008106516'" >> .env.local 
        echo -e "NEXT_PUBLIC_DISCORD_REDIRECT_URI=https%3A%2F%2Fddu.gg/inq" >> .env.local 
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Setup Deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@v1.1.2
      with:
        deno-version: ${{ matrix.deno-version }}
    
    - name: Blockchain - build and test
      working-directory: blockchain
      run: |
        deno lint src --rules-exclude=no-unused-vars,require-await
    
    - name: Blockchain - Build, tag, and push
      working-directory: blockchain
      env:
        REGISTRY: registry.digitalocean.com/ddu-cr
        REPOSITORY: ddu-blockchain
        IMAGE_TAG: mainnet # a-${{ steps.date.outputs.date }}-${{ github.sha }}
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY_MAINNET }}
      run: |
        echo "Image name $REGISTRY/$REPOSITORY:$IMAGE_TAG"
        deno task secrets:replace
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
